### ISSUE TITLE
what about non-parametric priors such as Johnson et. al 2016?

### ISSUE THREAD

**Issue by sameerkhurana10** [emtiyaz/vmp-for-svae#2]
could this approach be applied to cases when we have non-parametric PGMs such as the DP Mixture Model?

**Comment by emtiyaz** [comment]
Yes, for DP mixtures, you could choose a conditionally-conjugate model where you can use VMP to compute Z and produce samples (e.g. http://www.cs.columbia.edu/~blei/papers/BleiJordan2004.pdf). This might be computationally expensive since you need to run the VMP algorithm (such as the one suggested in the above paper) until convergence, but you can reduce computation by doing something approximate, e.g., see the  discussion in Appendix A in the paper (https://arxiv.org/abs/1803.05589).

Hope this helps!

**Comment by sameerkhurana10** [comment]
thanks, will try it out.
